#!/bin/bash

read isinvert < ~/isinvert

# if [ $isinvert = 'true' ]; then
#
#     echo $isinvert
#     echo 'false' > ~/isinvert
# else
#     echo 'true' > ~/isinvert
# fi

# invert all colors of the screen

$isinvert && isinvert=false || isinvert=true
echo $isinvert > ~/isinvert

xcalib -i -a &> /dev/null || exit 1
